language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - rbx-19mode

notifications:
  email: false

matrix:
  allow_failures:
    - rvm: rbx-19mode

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c 'create database storyteller_test;' -U postgres
  - bundle exec rake db:migrate
